{% set name = "datasette-leaflet" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datasette-leaflet-{{ version }}.tar.gz
  sha256: 8fd4e634304be392ae6f7de770d4f22b95a37caecd676a35faeb6200da9423bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - datasette

test:
  imports:
    - datasette_leaflet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonw/datasette-leaflet
  summary: A plugin that bundles Leaflet.js for Datasette
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
